### ISSUE TITLE
5 minutes

### ISSUE THREAD

**Issue by rvosa** [naturalis/trait-geo-diverse-ungulates#16]
hoe lang zou het duren om alles voor 5 arc minutes te draaien?

**Comment by ElkeHendrix** [comment]
weet ik niet. ik heb een tijdje geleden geprobeerd om er een proef te draaien, maar die bestanden waren te groot om binnen R op mijn laptop te runnen.

**Comment by rvosa** [comment]
Hoeveel RAM heb jij op je laptop?

**Comment by ElkeHendrix** [comment]
het probleem was de limit van R zelf. Ik zoek even uit of ik deze kan verhogen.

**Comment by ElkeHendrix** [comment]
als ik verder niks op mijn laptop aan heb staan kan ik er nu 3 tegelijk runnen. en het duurt niet veel langer met 5 minutes.

**Comment by rvosa** [comment]
Hoera!
