### ISSUE TITLE
Wilde voorouders

### ISSUE THREAD

**Issue by rvosa** [naturalis/trait-geo-diverse-ungulates#3]
Veruit de meeste soorten zijn wild, dus de huidige waarnemingen komen in belangrijke mate overheen met hun niche gedurende het hele Holoceen. Voor gedomesticeerde soorten is dat niet zo: ze zijn gefokt voor verschillende landschapstypen en worden bijgevoerd en in stallen gehouden. Idealiter zouden we de modellen dus baseren op (subfossiele?) waarnemingen van hun wilde voorouders. Dat betekent misschien ook dat we dus paleoklimaat moeten meenemen?

**Comment by ElkeHendrix** [comment]
In de dataset zitten dus waarnemingen die honderden jaren eerder of later gemaakt zijn. Als we klimaatvariabelen bekijken zoals de meest gebruikte Bioclimatic dataset dat kijken we alleen naar het gemiddelde van 1970 tot 2000.  (bekijken hoe het onderzoek naar de oeros is gedaan?)

Daarnaast zijn de waarnemingen van de gedomesticeerde soorten moeilijk omdat het niet duidelijk is of dit waarnemingen zijn in het wild? of dat dit waarnemingen zijn in een stal?

**Comment by rvosa** [comment]
Hopelijk is een redelijke benadering als volgt:
- voor elke gedomesticeerde soort zoeken we uit wat de wilde voorouder was (bijvoorbeeld: _Bos taurus_ => _Bos primigenius_)
- we zoeken alle beschikbare occurrences bij elkaar. Wellicht zijn dit (sub)fossiele specimens, als de wilde voorouder uitgestorven is, wat voor een aantal gedomesticeerde soorten zo is.
- voor de (sub)fossiele specimens verwijderen we alle records die Pleistoceen zijn.
- voor de records die overblijven maken we een selectie zodanig dat we de eigenaars van de specimens kunnen benaderen om te vragen wat ze weten over de dateringen.
- als de datering bekend is filteren we verder om alleen records uit het Holoceen over te houden.
- voor deze records gebruiken we de huidige WorldClim data als proxy voor het hele Holoceen.

**Comment by rvosa** [comment]
Vanaf commit https://github.com/naturalis/trait-geo-diverse-ungulates/commit/c6a194cc75fdec3bf3c61bced2008dcec9e5d214 zitten er in data/domesticated subfolders voor de diverse gedomesticeerde soorten, met daarin zip files met DarwinCore archive data. Voor elk van deze soorten is de query net weer een beetje anders geweest, daarom bewaren we de DOI's van de GBIF bestanden zoals weergegeven in deze [tabel](https://github.com/naturalis/trait-geo-diverse-ungulates/blob/master/doc/README.md#domesticated-species)
