### ISSUE TITLE
Soil properties 

### ISSUE THREAD

**Issue by ElkeHendrix** [naturalis/trait-geo-diverse-ungulates#4]
In de literatuur kan ik nergens een species distribution model voor dieren vinden die soil properties meeneemt. De meeste modellen (met dieren) kijken naar klimaat en vegetatie. Vegetatie is natuurlijk een indirecte maat van de bodem kwaliteit. Ik denk dat voor het model wat we nu maken bodem niet belangrijk is maar als het model ook gebruikt wordt voor vegetatie dan zijn bodem kwaliteiten wel heel bepalend.

**Comment by ElkeHendrix** [comment]
Of misschien is bodem juist heel interessant. De Harmonized World Soil Database heeft allemaal kaarten die beschrijven of bepaalde bodems geschikt zijn voor crop production. Misschien komen bepaalde gedomesticeerde dieren voor op plekken die geschikt zijn hiervoor?

**Comment by rvosa** [comment]
Ik denk dat we allebei wel geloven dat vegetatie voor herbivoren eigenlijk bepalender is dan bodem en klimaat, en dat de twee laatsten in feite een indirecte rol spelen die zich manifesteert in de vegetatie. Alleen durf ik dat niet met zekerheid te zeggen, en is het misschien wel zo dat formeel verschillende vegetatietypen (bijvoorbeeld, steppe versus savanne) voor een grazer ongeveer hetzelfde zijn, en wellicht ook overeen komen voor wat betreft bepaalde klimaatsvariabelen. Ik durf het dus niet a priori te zeggen, en zou eigenlijk er voor willen kiezen om ze gewoon allemaal te testen en vervolgens in het stadium van #1 de keuze te maken.

**Comment by rvosa** [comment]
We gebruiken nu de volgende soil properties:

- BulkDensity_10min
- ClayPercentage_10min
- OrganicCarbon_10min
- PhCaCL_10min

@ElkeHendrix, kan je nog even toelichten waar deze selectie op is gebaseerd?

**Comment by ElkeHendrix** [comment]
Ik heb de selectie uit het volgende artikel gehaald : Hageer, Y., Esperón-Rodríguez, M., Baumgartner, J. B., & Beaumont, L. J. (2017). Climate, soil or both? Which variables are better predictors of the distributions of Australian shrub species?. PeerJ, 5, e3446. In dit artikel staat dat deze variabelen de grootste invloed hebben op welke vegetatie er groeit en omdat we naar grazers kijken denk ik dat de invloed van de bodem op vegetatie het belangrijkst is (en  deze variabelen niet aan elkaar gecorreleerd zijn).
