### ISSUE TITLE
Niche modelleer vragen:

### ISSUE THREAD

**Issue by rvosa** [naturalis/trait-geo-diverse-ungulates#7]
- wat is een goede benadering/package voor ensembles?
- wat is een redelijke manier om buffering te automatiseren (hoe veel % rondom occurrences)?
- wat is een redelijke manier om variable selection te automatiseren (#1)?
- hoe valideren we de modellen (AUC, congruentie van projectie en occurrences)? (#2)?
- hoe gaan we de data opschonen (#8)?
- hoe gaan we om met categorische variabelen (bodem, vegetatie)?

**Comment by rvosa** [comment]
Mensen om mee te overleggen:
- Tom van Dooren, omdat hij ooit "niche traits" heeft geconstrueerd (middels PCA)
- Vincent Merckx, is zelf ook bezig met ontwikkelen van SDM strategie voor ERC aanvraag
- Niels Raes, SDM expert, auteur van [hoofdstuk](https://github.com/naturalis/mebioda/blob/master/doc/week2/w2d5/Raes_Aguirre_2018_ch21.pdf)
- Rosaleen March, SDM expert, bijdrager aan mebioda
- Nuno, SDM expert, bijdrager aan mebioda
- Maarten van 't Zelfde, GIS expert

**Comment by ElkeHendrix** [comment]
Hoeveel ruimte moet er om de abiotic data gehouden worden? Je cropt dus de abiotic rasters op de occurence punten maar je wilt dit niet meteen afsnijden, hoeveel laat je dan over? Verschillende buffer ruimtes zorgen voor hele grote verschillen in de resultaten.

**Comment by ElkeHendrix** [comment]
moet je per locatie berekenen of de abiotic layers gecorreleerd zijn? of kan je dit ook in een keer wereldwijd doen? het lijkt mij logisch dat als de layers lokaal gecorreleerd zijn dat ze dat wereldwijd ook zijn.

**Comment by ElkeHendrix** [comment]
Ik probeer nu te bedenken hoe we de maxent outputs met elkaar gaan vergelijken --> hievoor heb je eigenlijk data op wereldwijde schaal nodig voor alle species. Ik crop nu alle data + 500 km om de occurence points heen. Maar hierdoor krijg ja alleen de locaties binnen deze crop die geschikt zijn voor de soorten. Je neemt dus niet alle mogelijke locaties wereldwijd mee. Daarnaast levert het croppen van de environmental dataset het probleem op dat je ze later niet goed met elkaar kunt vergelijken --> om  Schoener’s D te kunnen berekenen heb je ene uniforme dataset per soort nodig (zelfde extent dus). De resultaten die ik nu genereer door te croppen zijn niet vergelijkbaar.

**Comment by rvosa** [comment]
> Ik probeer nu te bedenken hoe we de maxent outputs met elkaar gaan vergelijken --> hievoor heb je eigenlijk data op wereldwijde schaal nodig voor alle species. Ik crop nu alle data + 500 km om de occurence points heen. Maar hierdoor krijg ja alleen de locaties binnen deze crop die geschikt zijn voor de soorten. Je neemt dus niet alle mogelijke locaties wereldwijd mee. Daarnaast levert het croppen van de environmental dataset het probleem op dat je ze later niet goed met elkaar kunt vergelijken --> om Schoener’s D te kunnen berekenen heb je ene uniforme dataset per soort nodig (zelfde extent dus). De resultaten die ik nu genereer door te croppen zijn niet vergelijkbaar.

Ik geloof dat dat niet zo is. Weliswaar crop je de layers tot soortspecifieke gebieden die wellicht niet overlappen bij het vergelijken - maar dat is alleen voor het trainen van het model. Vervolgens projecteer je de modellen wereldwijd, en dan kan je de vergelijking dus wel maken.

**Comment by ElkeHendrix** [comment]
Jaa dat bedoelde ik precies. Dus voor mijn voorspelling maak ik wel een wereldwijde kaart alleen voor het trainen gebruik ik de cropped abiotic data.

**Comment by rvosa** [comment]
Ik ga dit issue sluiten, met de volgende conclusies:

- Tom en Niels zijn erg behulpzaam geweest
- vooralsnog hebben we Maarten niet rechstreeks nodig gehad, al zou dat er tzt wel van kunnen komen
- in de loop van het aankomende deep learning project nemen we nog wel contact op met Rosaleen en Nuno
