### ISSUE TITLE
Correlatie 

### ISSUE THREAD

**Issue by ElkeHendrix** [naturalis/trait-geo-diverse-ungulates#9]
Als we de correlatie tussen de abiotic lagen per species gaan berekenen weet ik niet of we de maxent resultaten wel met elkaar kunnen vergelijken (omdat je dan andere input in het model stopt).

**Comment by rvosa** [comment]
Volgens mij is de vergelijking gebaseerd op de projectie van habitat suitability, dus uiteindelijk gewoon op pixelwaardes, ongeacht waar die op gebaseerd zijn.
